version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  user-service:
    build: ./backend/user_service
    ports:
      - "5000:5000"
  
  product-service:
    build: ./backend/product_service
    ports:
      - "5001:5001"
  
  order-service:
    build: ./backend/order_service
    ports:
      - "5002:5002"